typography_spectrum: 0.5848267
content_rating:
  adult: false
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#FFFFFF'
    - '#00A0E0'
    - '#E3007E'
    - '#1D1D1B'
    - '#F185BF'
  lightness: 0.4713261
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b86dfaf-5cfb-4264-959f-b7a2646552a9.gif
layout_spectrum: 0.8882915
author:
  name: Besiana Bandilli
  email: bandillib@gmail.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3109f7b-0d1c-4f17-8a48-3c26a9fc6a03.gif
name: BB
navigation:
  - name: Who am I?
    id: cd665aa0-ba6f-4e00-ac66-b17706c7c450
    type: content
  - name: My Work
    id: 2b959a92-20d9-461f-b265-ae1bdcc3e4e9
    type: content
  - name: Contact Me
    id: 5d4e929b-6b87-4574-9d1f-9cc5e9ec7a63
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8cfcae9-d363-480a-bef6-72bc711650b1.gif
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Besiana Bandilli
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5f3f1176-fd02-4337-b6a7-a89626ce6e05.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5f3f1176-fd02-4337-b6a7-a89626ce6e05.gif
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/775e0e81-6786-47e3-9439-81b58e146a55.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/775e0e81-6786-47e3-9439-81b58e146a55.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7eeb1d6f-8670-4b9b-9fec-911761865c15.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7eeb1d6f-8670-4b9b-9fec-911761865c15.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d5107c16-3197-4afd-8044-ff23b34cdb08.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d5107c16-3197-4afd-8044-ff23b34cdb08.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: UX DESIGNER
purpose:
  - type: contact
    url: 'mailto:bandillib@gmail.com'
    label: 'Contact '
