title: Learn something new every day
content: []
github: true
purpose:
  - type: contact
    url: 'mailto:bandillib@gmail.com'
    label: Contact me
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Trial and error
color:
  saturation: 0.829749
  brandStrength: 1
  lightness: 0.8470532
  brandColors:
    - '#FFFFFF'
    - '#FBFC00'
    - '#00FCFD'
    - '#3F47CC'
    - '#979C96'
  rhythmicContrast: 0.8142174
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8cfcae9-d363-480a-bef6-72bc711650b1.gif
author:
  name: Besiana Bandilli
  email: bandillib@gmail.com
  url: ''
name: BB
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b86dfaf-5cfb-4264-959f-b7a2646552a9.gif
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3109f7b-0d1c-4f17-8a48-3c26a9fc6a03.gif
typography_spectrum: 0.4761051
layout_spectrum: 0.9611708
content_rating:
  adult: false
