typography_spectrum: 0.588411
content_rating:
  adult: false
color:
  saturation: 0.9937970887403935
  brandStrength: 0.8475520885549486
  rhythmicContrast: 0.1820328815374523
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  lightness: 0.5606211272533983
github: true
layout_spectrum: 0.9189428288955241
author:
  name: Besiana Bandilli
  email: bandillib@gmail.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8dd1c489-fd11-493f-9d0b-9d1cfe4810be.gif
name: Besiana Bandilli
navigation:
  - name: About me
    id: 6e7c909a-1ee5-4af4-91e5-0e0d55ce8714
    type: content
  - name: Skills
    id: daced828-708c-4bfc-9060-ef17c68007f3
    type: content
  - name: I am passionate about
    id: 7654100b-d584-4a76-b5e8-b712257325f8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8228f7ee-07de-4d17-a8df-d861dd631da4.gif
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Love something new every day
description: Trial and error
purpose:
  - type: internal
    label: Skills
    item: daced828-708c-4bfc-9060-ef17c68007f3
  - type: contact
    url: 'mailto:bandillib@gmail.com'
    label: Contact
