description: UX UI and Graphic Designer
typography_spectrum: 0.5848267
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b86dfaf-5cfb-4264-959f-b7a2646552a9.gif
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
author:
  name: Besiana Bandilli
  email: bandillib@gmail.com
  url: ''
layout_spectrum: 0.8882915
title: Besiana Bandilli
purpose:
  - type: contact
    url: 'mailto:bandillib@gmail.com'
    label: 'Contact '
github: true
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#FFFFFF'
    - '#00A0E0'
    - '#E3007E'
    - '#1D1D1B'
    - '#F185BF'
  lightness: 0.4713261
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3109f7b-0d1c-4f17-8a48-3c26a9fc6a03.gif
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8cfcae9-d363-480a-bef6-72bc711650b1.gif
content_rating:
  adult: false
name: BB
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c62944e2-f848-4fd0-b0d6-5b2118034dc6.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c62944e2-f848-4fd0-b0d6-5b2118034dc6.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
