typography_spectrum: 0.1547192
content_rating:
  adult: false
color:
  saturation: 1
  brandStrength: 0.9086021
  rhythmicContrast: 1
  brandColors:
    - '#000000'
    - '#FFFF18'
    - '#17FBFF'
    - '#FF00FB'
    - '#0D94AF'
  lightness: 0.4928315
github: true
layout_spectrum: 0.9181601
author:
  name: Besiana Bandilli
  email: bandillib@gmail.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/91d364b0-e385-437c-be61-ed8fb12477cd.gif
name: BB
navigation:
  - name: About
    id: cd665aa0-ba6f-4e00-ac66-b17706c7c450
    type: content
  - name: Passion
    id: 61afb10a-1ffe-4ff6-ba67-6191c2ac40ed
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/51b29a98-89c1-4605-8ed3-805c5b71b0aa.gif
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Love something new every day
description: Trial and error
purpose:
  - type: internal
    label: Skills
    item: 1e7335fc-e550-4745-8255-c5bbc68d54bc
  - type: contact
    url: 'mailto:bandillib@gmail.com'
    label: Contact me
