name: BB
analytics:
  google: UA-104083424-1
purpose:
  - type: contact
    url: 'mailto:bandillib@gmail.com'
    label: Contact me
github: true
description: ''
author:
  name: Besiana Bandilli
  email: bandillib@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e0601f1-4f50-4e4e-90a4-7113a0ec27c4.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e0601f1-4f50-4e4e-90a4-7113a0ec27c4.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - name: About me
    id: cd665aa0-ba6f-4e00-ac66-b17706c7c450
    type: content
  - name: Contact Me
    id: 5d4e929b-6b87-4574-9d1f-9cc5e9ec7a63
    type: content
layout_spectrum: 0.676271912052416
color:
  lightness: 0.444944266237337
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  saturation: 0.5126932689130749
  brandStrength: 0.530126575470192
  rhythmicContrast: 0.6177388074806901
content_rating:
  adult: false
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d9a3727d-6fea-4383-9fae-8c0f6e1e06ea.png
typography_spectrum: 0.3545214236073085
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b86dfaf-5cfb-4264-959f-b7a2646552a9.gif
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c57d216-7e7f-40ad-bae5-06f25f646c0c.png
title: >-
  I'm a visual and interaction designer. I love what I do. I'm curious,
  ambitious, and motivated to learn something new every day.
