layout_spectrum: 0.676271912052416
typography_spectrum: 0.3545214236073085
color:
  saturation: 0.5126932689130749
  brandStrength: 0.530126575470192
  rhythmicContrast: 0.6177388074806901
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  lightness: 0.44494426623733696
content_rating:
  adult: false
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b86dfaf-5cfb-4264-959f-b7a2646552a9.gif
author:
  name: Besiana Bandilli
  email: bandillib@gmail.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3109f7b-0d1c-4f17-8a48-3c26a9fc6a03.gif
name: BB
navigation:
  - name: Who am I?
    id: cd665aa0-ba6f-4e00-ac66-b17706c7c450
    type: content
  - name: My Work
    id: 2b959a92-20d9-461f-b265-ae1bdcc3e4e9
    type: content
  - name: Contact Me
    id: 5d4e929b-6b87-4574-9d1f-9cc5e9ec7a63
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8cfcae9-d363-480a-bef6-72bc711650b1.gif
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Besiana Bandilli
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f2568af3-4e25-40d5-86da-99e012b2651a.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f2568af3-4e25-40d5-86da-99e012b2651a.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: UX DESIGNER
purpose:
  - type: contact
    url: 'mailto:bandillib@gmail.com'
    label: 'Contact '
