title: Learn something new every day
content: []
github: true
purpose:
  - type: contact
    url: 'mailto:bandillib@gmail.com'
    label: 'Contact '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Besiana Bandilli UX Designer
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.4701314
  brandColors:
    - '#FFFC00'
    - '#FFFFFF'
    - '#03BBCB'
    - '#000000'
    - '#A9E645'
  rhythmicContrast: 1
navigation:
  - name: About
    id: 5614b562-6491-4c2b-9063-aa03c463fe52
    type: content
  - name: Portfolio
    id: 2b959a92-20d9-461f-b265-ae1bdcc3e4e9
    type: content
  - name: Contact
    id: 0925f154-d8b1-4888-a404-8777aabfe22e
    type: content
  - name: Resume
    id: 6d7178f9-72bd-4e33-b6c2-b5b82590331f
    type: content
name: BB
author:
  name: Besiana Bandilli
  email: bandillib@gmail.com
  url: ''
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8cfcae9-d363-480a-bef6-72bc711650b1.gif
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b86dfaf-5cfb-4264-959f-b7a2646552a9.gif
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3109f7b-0d1c-4f17-8a48-3c26a9fc6a03.gif
typography_spectrum: 0.5848267
layout_spectrum: 0.9265233
content_rating:
  adult: false
