title: Love something new every day
github: true
purpose:
  - type: internal
    label: Skills
    item: daced828-708c-4bfc-9060-ef17c68007f3
  - type: contact
    url: 'mailto:bandillib@gmail.com'
    label: Contact
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Trial and error
color:
  saturation: 1
  brandStrength: 0.8751493
  lightness: 0.551374
  brandColors:
    - '#000000'
    - '#FE0080'
    - '#33FE00'
    - '#F4FD00'
    - '#808080'
  rhythmicContrast: 0.9026284
navigation:
  - name: About me
    id: cd665aa0-ba6f-4e00-ac66-b17706c7c450
    type: content
  - name: Passion
    id: 61afb10a-1ffe-4ff6-ba67-6191c2ac40ed
    type: content
  - name: Skills
    id: 1e7335fc-e550-4745-8255-c5bbc68d54bc
    type: content
  - name: Portfolio
    id: 2b959a92-20d9-461f-b265-ae1bdcc3e4e9
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/51b29a98-89c1-4605-8ed3-805c5b71b0aa.gif
name: BB
author:
  name: Besiana Bandilli
  email: bandillib@gmail.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/91d364b0-e385-437c-be61-ed8fb12477cd.gif
typography_spectrum: 0.3704555949661881
layout_spectrum: 0.9360812
content_rating:
  adult: false
