layout_spectrum: 0.5268552410416305
typography_spectrum: 0.27508429740555584
color:
  saturation: 0.41522851516492665
  brandStrength: 0.35452492046169937
  rhythmicContrast: 0.5305410323198885
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  lightness: 0.27207902586087584
content_rating:
  adult: false
github: true
author:
  name: Besiana Bandilli
  email: bandillib@gmail.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/91d364b0-e385-437c-be61-ed8fb12477cd.gif
name: BB
navigation:
  - name: About me
    id: cd665aa0-ba6f-4e00-ac66-b17706c7c450
    type: content
  - name: Passion
    id: 61afb10a-1ffe-4ff6-ba67-6191c2ac40ed
    type: content
  - name: Skills
    id: 1e7335fc-e550-4745-8255-c5bbc68d54bc
    type: content
  - name: Portfolio
    id: 2b959a92-20d9-461f-b265-ae1bdcc3e4e9
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/51b29a98-89c1-4605-8ed3-805c5b71b0aa.gif
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Love something new every day
description: Trial and error
purpose:
  - type: internal
    label: Skills
    item: daced828-708c-4bfc-9060-ef17c68007f3
  - type: contact
    url: 'mailto:bandillib@gmail.com'
    label: Contact
